import { Link } from 'react-router-dom';
import { usePageTitle } from '../utils/usePageTitle';

function Section({ title, children }) {
  return (
    <section className="mb-8">
      <h2 className="font-display text-xl font-bold text-ink mb-3">{title}</h2>
      <div className="space-y-3 text-sm text-coffee-700 leading-relaxed">{children}</div>
    </section>
  );
}

export default function Terms() {
  usePageTitle('Terms of Service');
  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <span className="inline-flex items-center gap-1.5 text-xs font-mono uppercase tracking-widest text-coffee-500 mb-3">
        Legal
      </span>
      <h1 className="display-heading text-3xl sm:text-4xl text-ink mb-2">Terms of Service</h1>
      <p className="text-xs text-coffee-500 mb-10">Last updated: 19 July 2026</p>

      <p className="text-sm text-coffee-700 leading-relaxed mb-8">
        By using Areté, you agree to these terms. Please read them — if something here doesn't work for you, contact
        us before continuing to use the platform.
      </p>

      <Section title="1. What Areté is">
        <p>
          Areté is an independent, student-built academic companion for B.Sc. Cybersecurity students at the
          University of Uyo — a curriculum browser, programming tracks, an AI tutor, and study tools. It is not an
          official University of Uyo service and isn't endorsed by the university's administration.
        </p>
      </Section>

      <Section title="2. Your account">
        <p>
          You must provide accurate information when setting up your profile and keep your sign-in access secure.
          One account per person. You're responsible for activity that happens under your account.
        </p>
      </Section>

      <Section title="3. Acceptable use">
        <ul className="list-disc pl-5 space-y-2">
          <li>Don't use the AI Tutor, Code Explainer, or CTF challenge answers to violate your course's academic integrity policy — Areté is a study aid, not a shortcut around your own learning or assessments.</li>
          <li>Don't attempt to bypass rate limits, security controls, or the intended use of any feature (including the CTF security rooms, which are for learning, not for attacking other users or systems).</li>
          <li>Don't upload course materials you don't have the right to share.</li>
          <li>Don't use the platform to harass, impersonate, or share others' personal data without consent.</li>
        </ul>
      </Section>

      <Section title="4. Content you upload">
        <p>
          You retain ownership of course materials you upload. By uploading, you grant Areté a license to store
          and display that content to other signed-in students viewing the same course. You're responsible for
          having the right to share whatever you upload.
        </p>
      </Section>

      <Section title="5. AI-generated content">
        <p>
          Responses from the AI Tutor, Code Explainer, Explain-this, and Simplify-this are generated by third-party
          AI models and can be incomplete or wrong. They're a study aid, not a substitute for your lecturer, course
          materials, or your own verification — especially before an exam.
        </p>
      </Section>

      <Section title="6. Third-party services">
        <p>
          Some features rely on external services — code execution (JDoodle), AI providers (Groq, Google Gemini,
          OpenRouter), and, if you connect it, Google Calendar. Your use of those features is also subject to
          those providers' own terms. See our <Link to="/privacy" className="font-medium text-ink underline hover:text-ember">Privacy Policy</Link> for the full list.
        </p>
      </Section>

      <Section title="7. Free service, provided as-is">
        <p>
          Areté is provided free of charge, on a best-effort basis, with no uptime guarantee. Some features have
          usage limits (for example, the Code Playground shares a pool of 20 free executions/day across all
          students) and may be temporarily unavailable if a limit is reached or a provider is down.
        </p>
      </Section>

      <Section title="8. Suspension and termination">
        <p>
          We may suspend or terminate access for accounts that violate section 3 (acceptable use) or otherwise
          abuse the platform. You can stop using Areté and request account deletion at any time — see the Privacy
          Policy for how.
        </p>
      </Section>

      <Section title="9. Limitation of liability">
        <p>
          Areté is provided "as is" without warranties of any kind. To the extent permitted by law, we're not
          liable for damages arising from your use of the platform, including reliance on AI-generated content or
          downtime of a third-party service we depend on.
        </p>
      </Section>

      <Section title="10. Governing law">
        <p>These terms are governed by the laws of the Federal Republic of Nigeria.</p>
      </Section>

      <Section title="11. Changes to these terms">
        <p>We'll update the "last updated" date above when these terms change. Material changes will be noted on this page.</p>
      </Section>

      <Section title="12. Contact">
        <p>Questions about these terms: <a href="mailto:robertsunday333@gmail.com" className="font-medium text-ink underline hover:text-ember">robertsunday333@gmail.com</a></p>
      </Section>
    </div>
  );
}
